import express from "express";
import authRoute from "./auth.route";
import chatRoute from "./chat.route";
import legalRagRoute from "./legal-rag.route";
import filesRoute from "./files.route";
import usersRoute from "./users.route";
import caseRoute from "./case.route";
import bookmarkRoute from "./bookmark.route";
import userDocumentRoute from "./user-document.route";
import legalSourceCacheRoute from "./legal-source-cache.route";
import transcriptionRoute from "./transcription.route";
import eventRoute from "./event.route";
import calendarRoute from "./calendar.route";
import legalRoute from "./legal.route";
import sendEmailRoute from "./send-email.route";
import rsvpRoute from "./rsvp.route";
import ttsRoute from "./tts.route";
import healthRoute from "./health.route";
import caseDocumentRoute from "./case-document.route";
import terminalRoute from "./terminal.route";
import organizationRoute from "./organization.route";
import { jurisdictionRouter, integrationRouter } from "./jurisdiction.route";
import modelSettingsRoute from "./model-settings.route";

const router = express.Router();

router.use("/health", healthRoute);
router.use("/organizations", organizationRoute);
router.use("/case-document", caseDocumentRoute);
router.use("/auth", authRoute);
router.use("/chat", chatRoute);
router.use("/legal-rag", legalRagRoute);
router.use("/files", filesRoute);
router.use("/users", usersRoute);
router.use("/my-cases", caseRoute);
router.use("/bookmarks", bookmarkRoute);
router.use("/documents", userDocumentRoute);
router.use("/legal-source-analysis", legalSourceCacheRoute);
router.use("/transcriptions", transcriptionRoute);
router.use("/events", eventRoute);
router.use("/calendar", calendarRoute);
router.use("/legal", legalRoute);
router.use("/send-email", sendEmailRoute);
router.use("/rsvp", rsvpRoute);
router.use("/tts", ttsRoute);
router.use("/terminal", terminalRoute);
router.use("/jurisdictions", jurisdictionRouter);
router.use("/integrations", integrationRouter);
router.use("/model-settings", modelSettingsRoute);

export default router;
