/** Which security audit actions each route writes — or why it writes none. One entry per mutating
 * route (and per GET that exports, downloads or resolves a file), keyed "METHOD /path" as mounted
 * under /api. test/security-audit-coverage.spec.ts fails when a route is missing from here, so a
 * new endpoint can't ship without someone deciding whether it belongs in the security audit log
 * (docs/adr/0006-security-audit-log.md). An exemption is a reason, not a loophole: if a route
 * starts touching sign-in, permissions, exports, downloads or deletion, it moves to an action list.
 */
import type { SecurityAuditAction } from "../../src/constants/security-audit.constants";

export interface Exempt {
  exempt: string;
}

const CASE_FEED: Exempt = {
  exempt: "Creates or edits case/consultation content — not a Tier 1 security event; the case activity feed (AuditEvent) records most of these",
};
const AI_RUN: Exempt = {
  exempt: "AI generation or legal search — Tier 2 (audit plan issue E); most case-level runs already write AuditEvent",
};
const UPLOAD: Exempt = { exempt: "Uploads a file — adding data, not access to or removal of it; document.ready lands in the case activity feed" };
const SESSION: Exempt = { exempt: "Keeps an existing session or grant alive (token rotation, OTP resend) — the sign-in itself is recorded" };
const PERSONAL: Exempt = { exempt: "The user's own calendar, bookmarks or notes — not client-matter access" };
const UI_STATE: Exempt = { exempt: "Personal UI state (terminal layouts, presets, tours, notification read marks)" };
const PROFILE_COSMETIC: Exempt = { exempt: "Avatar image — cosmetic profile change" };
const SYSTEM: Exempt = { exempt: "Google Calendar push-notification plumbing, called by Google or the sync job" };
const TIER2_READ: Exempt = { exempt: "Opening a case — a read, Tier 2 (audit plan issue E)" };
const READ: Exempt = { exempt: "Lists past exports; each download through its link is recorded as file.accessed" };
const INTEGRATION_DRAFT: Exempt = { exempt: "Creates a disconnected connector record; connecting it is recorded" };

export const SECURITY_AUDIT_COVERAGE: Record<string, readonly SecurityAuditAction[] | Exempt> = {
  "POST /organizations/": ["org.created"],
  "POST /organizations/invites/:id/accept": ["org.invite_accepted", "org.member_left"],
  "POST /organizations/invites/:id/decline": ["org.invite_declined"],
  "PATCH /organizations/:id": ["org.updated"],
  "POST /organizations/:id/members": ["org.member_invited"],
  "PATCH /organizations/:id/members/:userId": ["org.member_role_changed"],
  "DELETE /organizations/:id/members/me": ["org.member_left"],
  "DELETE /organizations/:id/members/:userId": ["org.member_removed"],
  "POST /organizations/:id/cases": ["org.case_attached"],
  "GET /organizations/:id/audit-log/export": ["export.audit_log"],
  "POST /generated-document/": ["export.generated_document"],
  "POST /auth/signup": ["auth.signup"],
  "POST /auth/send-otp": SESSION,
  "POST /auth/cancel-signup": ["auth.signup_cancelled"],
  "POST /auth/verify-otp": ["auth.email_verified", "auth.login"],
  "POST /auth/login": ["auth.login"],
  "POST /auth/update-required-password": ["auth.password_changed", "auth.login"],
  "POST /auth/refresh": SESSION,
  "POST /auth/logout": ["auth.logout"],
  "POST /auth/google": ["auth.login", "auth.signup"],
  "POST /auth/google/link": ["auth.google_linked", "auth.login"],
  "POST /auth/google/refresh": SESSION,
  "POST /auth/forgot-password": ["auth.password_reset_requested"],
  "POST /auth/reset-password": ["auth.password_reset", "auth.login"],
  "POST /auth/login-link/consume": ["auth.login"],
  "POST /chat/consultations": CASE_FEED,
  "PATCH /chat/consultations/:consultationId": CASE_FEED,
  "POST /chat/consultations/:consultationId/archive": CASE_FEED,
  "POST /chat/consultations/:consultationId/unarchive": CASE_FEED,
  "DELETE /chat/consultations/:consultationId": ["consultation.deleted"],
  "POST /chat/consultations/:consultationId/relevant-chunks": AI_RUN,
  "POST /chat/consultations/:consultationId/messages": AI_RUN,
  "POST /chat/consultations/:consultationId/messages/:messageId/cancel": CASE_FEED,
  "DELETE /chat/consultations/:consultationId/messages/:messageId": ["consultation.message_deleted"],
  "POST /chat/consultations/:consultationId/messages/:messageId/audio-overview/audio": AI_RUN,
  "POST /chat/consultations/:consultationId/mind-map/expand": AI_RUN,
  "POST /chat/consultations/:consultationId/mind-map/revert": CASE_FEED,
  "PATCH /chat/consultations/:consultationId/mind-map": CASE_FEED,
  "POST /chat/consultations/:consultationId/invites": ["consultation.invite_created"],
  "POST /chat/invites/:id/accept": ["consultation.invite_accepted"],
  "DELETE /chat/invites/:id": ["consultation.invite_deleted"],
  "DELETE /chat/consultations/:consultationId/participants/:userId": ["consultation.participant_removed"],
  "POST /legal-rag/search-vector": AI_RUN,
  "POST /legal-rag/format-documents": AI_RUN,
  "POST /legal-rag/:id/format": AI_RUN,
  "POST /files/upload": UPLOAD,
  "GET /files/resolve": ["file.accessed"],
  "PATCH /users/me": ["account.profile_updated"],
  "POST /users/me/change-password": ["auth.password_changed"],
  "DELETE /users/me": ["account.deletion_requested"],
  "POST /users/me/cancel-deletion": ["account.deletion_cancelled"],
  "POST /users/me/export": ["export.my_data"],
  "PUT /consents/:purpose": ["consent.changed"],
  "PUT /users/me/avatar": PROFILE_COSMETIC,
  "DELETE /users/me/avatar": PROFILE_COSMETIC,
  "POST /users/me/google-calendar": ["integration.connected"],
  "DELETE /users/me/google-calendar": ["integration.disconnected"],
  "PUT /users/me/tour/:track": UI_STATE,
  "POST /admin/users/:id/export": ["export.user_data"],
  "POST /admin/users/:id/approve": ["admin.user.approved"],
  "POST /admin/users/:id/deny": ["admin.user.denied"],
  "POST /admin/users/:id/reactivate": ["admin.user.reactivated"],
  "POST /admin/users/:id/block": ["admin.user.blocked"],
  "POST /admin/users/:id/unblock": ["admin.user.unblocked"],
  "POST /admin/users/:id/verify-email": ["admin.user.email_verified"],
  "PATCH /admin/users/:id/tenant": ["admin.user.tenant_changed"],
  "DELETE /admin/users/:id": ["admin.user.deleted"],
  "PATCH /admin/settings/tenants/:code": ["admin.settings.signup_auto_approve_changed"],
  "POST /admin/tenants/:code/approve-pending": ["admin.user.approved"],
  "GET /admin/audit-log/export": ["export.audit_log"],
  "POST /law/:lawId/citations/expand": AI_RUN,
  "POST /my-cases/": CASE_FEED,
  "PATCH /my-cases/:id": CASE_FEED,
  "DELETE /my-cases/:id": ["case.deleted", "document.deleted"],
  "POST /my-cases/:id/opened": TIER2_READ,
  "POST /my-cases/:id/archive": CASE_FEED,
  "POST /my-cases/:id/unarchive": CASE_FEED,
  "POST /my-cases/archive": CASE_FEED,
  "POST /my-cases/unarchive": CASE_FEED,
  "DELETE /my-cases/": ["case.deleted", "document.deleted"],
  "POST /my-cases/:caseId/documents": UPLOAD,
  "POST /my-cases/:caseId/relevant-chunks": AI_RUN,
  "POST /my-cases/:caseId/refresh": AI_RUN,
  "POST /my-cases/:caseId/timeline": CASE_FEED,
  "POST /my-cases/:caseId/timeline/generate": AI_RUN,
  "PATCH /my-cases/:caseId/mind-map": CASE_FEED,
  "POST /my-cases/:caseId/mind-map/generate": AI_RUN,
  "POST /my-cases/:caseId/mind-map/expand": AI_RUN,
  "POST /my-cases/:caseId/mind-map/revert": CASE_FEED,
  "PATCH /my-cases/:caseId/timeline/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/timeline/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/risks": CASE_FEED,
  "PATCH /my-cases/:caseId/risks/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/risks/:id": ["case.item_deleted"],
  "PUT /my-cases/:caseId/evidence/matrix/:documentId": CASE_FEED,
  "POST /my-cases/:caseId/evidence/matrix/:documentId/custody": CASE_FEED,
  "DELETE /my-cases/:caseId/evidence/matrix/:documentId/custody/:eventId": ["case.item_deleted"],
  "POST /my-cases/:caseId/evidence/contradictions/scan": AI_RUN,
  "PATCH /my-cases/:caseId/evidence/contradictions/:id": CASE_FEED,
  "POST /my-cases/:caseId/evidence/missing/regenerate": AI_RUN,
  "PATCH /my-cases/:caseId/evidence/missing/:id": CASE_FEED,
  "POST /my-cases/:caseId/citations": CASE_FEED,
  "PATCH /my-cases/:caseId/citations/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/citations/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/citation-grounds/map": AI_RUN,
  "POST /my-cases/:caseId/citation-map/sweep": AI_RUN,
  "POST /my-cases/:caseId/citation-map/adverse/:id/accept": CASE_FEED,
  "POST /my-cases/:caseId/citation-map/adverse/:id/dismiss": CASE_FEED,
  "POST /my-cases/:caseId/citation-grounds": CASE_FEED,
  "DELETE /my-cases/:caseId/citation-grounds/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/authorities": CASE_FEED,
  "PATCH /my-cases/:caseId/authorities/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/authorities/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/edges": CASE_FEED,
  "DELETE /my-cases/:caseId/edges/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/strategy/refresh": AI_RUN,
  "POST /my-cases/:caseId/procedure/deadlines": CASE_FEED,
  "POST /my-cases/:caseId/procedure/deadlines/recompute-stale": AI_RUN,
  "POST /my-cases/:caseId/procedure/deadlines/:deadlineId/confirm": CASE_FEED,
  "POST /my-cases/:caseId/procedure/deadlines/:deadlineId/recompute": AI_RUN,
  "POST /my-cases/:caseId/procedure/items": CASE_FEED,
  "PATCH /my-cases/:caseId/procedure/items/:id": CASE_FEED,
  "POST /my-cases/:caseId/access": ["case.access_granted"],
  "POST /my-cases/:caseId/findings": CASE_FEED,
  "POST /my-cases/:caseId/findings/regenerate": AI_RUN,
  "POST /my-cases/:caseId/outlook/generate": AI_RUN,
  "PATCH /my-cases/:caseId/findings/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/findings/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/findings/:id/jev-check": AI_RUN,
  "POST /my-cases/:caseId/witnesses": CASE_FEED,
  "POST /my-cases/:caseId/witnesses/score": AI_RUN,
  "POST /my-cases/:caseId/witnesses/refresh": AI_RUN,
  "PATCH /my-cases/:caseId/witnesses/:id": CASE_FEED,
  "PATCH /my-cases/:caseId/witnesses/:id/factors/:factor": CASE_FEED,
  "DELETE /my-cases/:caseId/witnesses/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/damages": CASE_FEED,
  "POST /my-cases/:caseId/damages/propose": AI_RUN,
  "POST /my-cases/:caseId/damages/refresh": AI_RUN,
  "PATCH /my-cases/:caseId/damages/:id": CASE_FEED,
  "POST /my-cases/:caseId/damages/:id/accept": CASE_FEED,
  "DELETE /my-cases/:caseId/damages/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/claims/extract": AI_RUN,
  "POST /my-cases/:caseId/claims": CASE_FEED,
  "PATCH /my-cases/:caseId/claims/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/claims/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/reconstruction/generate": AI_RUN,
  "PATCH /my-cases/:caseId/reconstruction": CASE_FEED,
  "POST /my-cases/:caseId/reconstruction/scenes": AI_RUN,
  "POST /my-cases/:caseId/reconstruction/events": AI_RUN,
  "POST /my-cases/:caseId/red-team/generate": AI_RUN,
  "GET /my-cases/:caseId/export": ["export.case_brief"],
  "GET /my-cases/:caseId/export/history": READ,
  "POST /my-cases/:caseId/audio-overview/generate": AI_RUN,
  "POST /my-cases/:caseId/audio-overview/:overviewId/recording": AI_RUN,
  "POST /my-cases/:caseId/decisions/:id/dispute": CASE_FEED,
  "POST /my-cases/:caseId/decisions/:id/reactivate": CASE_FEED,
  "POST /my-cases/:caseId/theories": CASE_FEED,
  "POST /my-cases/:caseId/theories/propose": AI_RUN,
  "POST /my-cases/:caseId/theories/diff": AI_RUN,
  "PATCH /my-cases/:caseId/theories/:id": CASE_FEED,
  "DELETE /my-cases/:caseId/theories/:id": ["case.item_deleted"],
  "POST /my-cases/:caseId/theories/:id/publish": CASE_FEED,
  "POST /my-cases/:caseId/theories/:id/retire": CASE_FEED,
  "POST /my-cases/:caseId/theories/:id/fork": CASE_FEED,
  "POST /my-cases/:caseId/theories/:id/claims": CASE_FEED,
  "POST /my-cases/:caseId/theories/:id/assumptions": CASE_FEED,
  "POST /my-cases/:caseId/theories/:id/open-questions": CASE_FEED,
  "PATCH /my-cases/:caseId/theories/:id/claims/:itemId": CASE_FEED,
  "DELETE /my-cases/:caseId/theories/:id/claims/:itemId": ["case.item_deleted"],
  "PATCH /my-cases/:caseId/theories/:id/assumptions/:itemId": CASE_FEED,
  "DELETE /my-cases/:caseId/theories/:id/assumptions/:itemId": ["case.item_deleted"],
  "PATCH /my-cases/:caseId/theories/:id/open-questions/:itemId": CASE_FEED,
  "DELETE /my-cases/:caseId/theories/:id/open-questions/:itemId": ["case.item_deleted"],
  "POST /my-cases/:caseId/annotations": CASE_FEED,
  "POST /my-cases/:caseId/annotations/:id/resolve": CASE_FEED,
  "POST /my-cases/:caseId/annotations/:id/reopen": CASE_FEED,
  "POST /bookmarks/": PERSONAL,
  "DELETE /bookmarks/:id": PERSONAL,
  "POST /documents/presign": UPLOAD,
  "POST /documents/": UPLOAD,
  "PATCH /documents/:id": CASE_FEED,
  "DELETE /documents/:id": ["document.deleted"],
  "POST /documents/:id/archive": CASE_FEED,
  "POST /documents/:id/unarchive": CASE_FEED,
  "POST /documents/archive": CASE_FEED,
  "POST /documents/unarchive": CASE_FEED,
  "DELETE /documents/": ["document.deleted"],
  "POST /legal-source-analysis/": AI_RUN,
  "POST /transcriptions/": CASE_FEED,
  "POST /transcriptions/:id/start-job": AI_RUN,
  "POST /transcriptions/:id/chunk": AI_RUN,
  "PATCH /transcriptions/:id": CASE_FEED,
  "DELETE /transcriptions/:id": ["transcription.deleted"],
  "POST /events/": PERSONAL,
  "PUT /events/:id": PERSONAL,
  "PUT /events/by-google-id/:googleEventId": PERSONAL,
  "DELETE /events/:id": PERSONAL,
  "DELETE /events/by-google-id/:googleEventId": PERSONAL,
  "PUT /notifications/read-all": UI_STATE,
  "PUT /notifications/:id/read": UI_STATE,
  "POST /notes/": PERSONAL,
  "PUT /notes/:id": PERSONAL,
  "DELETE /notes/:id": ["note.deleted"],
  "POST /calendar/webhooks/calendar": SYSTEM,
  "POST /calendar/watch": SYSTEM,
  "POST /send-email/": ["email.sent"],
  "POST /rsvp/:eventId": PERSONAL,
  "POST /tts/polly": AI_RUN,
  "POST /terminal/workspaces": UI_STATE,
  "POST /terminal/workspaces/reset": UI_STATE,
  "PATCH /terminal/workspaces/:id": UI_STATE,
  "POST /terminal/workspaces/:id/apply": UI_STATE,
  "DELETE /terminal/workspaces/:id": UI_STATE,
  "POST /terminal/screen-presets": UI_STATE,
  "PATCH /terminal/screen-presets/:id": UI_STATE,
  "DELETE /terminal/screen-presets/:id": UI_STATE,
  "PATCH /jurisdictions/:code": ["admin.jurisdiction_module.toggled"],
  "POST /integrations/": INTEGRATION_DRAFT,
  "POST /integrations/:id/connect": ["integration.connected"],
  "POST /integrations/:id/disconnect": ["integration.disconnected"],
  "PUT /model-settings/:toolName": ["admin.model_settings.updated"],
};
