-- The immediately preceding migration (20260821065915) was auto-generated by
-- `prisma migrate dev` while reconciling an unrelated, pre-existing drift
-- (Case.organizationId becoming optional per schema.prisma) and, as a side effect,
-- dropped this HNSW vector index without recreating it. Restoring it here.
-- See 20260820133000_add_case_document_chunk_embedding_hnsw for the original.
CREATE INDEX "CaseDocumentChunk_embedding_hnsw_idx"
  ON "CaseDocumentChunk"
  USING hnsw (embedding vector_cosine_ops);
